### ISSUE TITLE
[20.15] CG Policy Group is now mandatory

### ISSUE THREAD

**Issue by larslilja** [cisco-open/sdwan-lab-deployment-tool#24]
## Description
In 20.15.137 and onwards Policy Group is now mandatory when you want to deploy a CG.  Which means that the tool needs to ensure to assign the policy group when deploying a new overlay. 

## Expected Behavior
Policy is attached by default.

## Actual Behavior
Policy group is not assigned.

## Affected Version
20.15.137 // Tool 2.0.13 

## Steps to Reproduce
1. Deploy 20.15.137 
2. try to deploy default CG
![image](https://github.com/cisco-open/sdwan-lab-deployment-tool/assets/134637825/e31e3613-d4e6-487f-827d-29dcd5a2c05f)

## Checklist

- [ x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ x] I have verified this does not duplicate an existing issue

**Comment by tzarski0** [comment]
https://github.com/cisco-open/sdwan-lab-deployment-tool/commit/56d28f06b3633c6c2f5f34b5a6e770a20c44d1a7
