### ISSUE TITLE
Stop using Factory default templates for controllers

### ISSUE THREAD

**Issue by larslilja** [cisco-open/sdwan-lab-deployment-tool#27]
## Problem Statement
When using factory default templates for controllers etc. then workflows will or user cant modify them afterwards.

## Proposed Solution
Please change the factory default templates to custom templates so they are able to be modified.

**Comment by tzarski0** [comment]
Hi @larslilja, we do not expect user to modify the basic templates we provide. If user would add any variable in the basic templates, then "add" task will stop working as it will not know how to fill those variables. This is why we put "Do not modify!" in the comments. We expect user to create a copy and do modifications in the copy (either copy the template we created or copy default template that is used). I guess it would still be valid not to use default templates so at least user can add new global values in basic feature templates. Is that what you are looking for?

**Comment by larslilja** [comment]
Hi @tzarski0 

I see your point, in this case it was the controller "device template" that uses factory defaults, wich will then impaired workflows coming after. So thats the once i want to change if possible.
