### ISSUE TITLE
Ability to use other bridge interfaces 

### ISSUE THREAD

**Issue by larslilja** [cisco-open/sdwan-lab-deployment-tool#36]
## Problem Statement
Today our external interface is defaulting to bridge0, if customers want to use another interface they would have to do a manual step. 

Please describe the problem to be addressed by the proposed feature.

## Proposed Solution
Can we add an optional knob to the source file so the user could add bridge1 or something as part of the deployment ? 

Please describe what you envision the solution to this problem would look like.

## Alternatives Considered

Please briefly describe which alternatives, if any, have been considered, including merits of alternate approaches and
tradeoffs being made.

## Additional Context

Please provide any other information that may be relevant.

**Comment by tzarski0** [comment]
Hi @larslilja, this is already supported with "--bridge <custom-bridge-name>" option in the deploy task. Could you please verify and let me know if any changes are required? Here's the doc from README.md:
```
--bridge <custom-bridge-name>
                          Set custom bridge for SD-WAN Manager external connection. Default is System Bridge
```

**Comment by larslilja** [comment]
Ohh, i hadn't catch that... :)
